# Generated by Django 4.0.5 on 2022-06-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Producto')),
                ('stock', models.IntegerField(verbose_name='Stock Producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion Producto')),
                ('imagen', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
